### ISSUE TITLE
Module veikk not found in directory /lib/modules/5.3.0-62-generic while doing sudo modprobe veikk

### ISSUE THREAD

**Issue by swarnak25** [jlam55555/veikk-linux-driver#38] opened 2020-08-04 20:30 UTC

**Comment by jlam55555** [comment] 2020-08-07 11:20
See [this issue](https://github.com/jlam55555/veikk-linux-driver/issues/27). The issue is caused by `depmod` not called by `modprobe` (only Ubuntu and its derivatives, I believe) and should've been fixed in https://github.com/jlam55555/veikk-linux-driver/commit/815cff1836e031d6d9a6fa988276d3c449cefe61.

(If you're cloning from the v3-alpha branch I might not have re-added in the `depmod` line yet, but I'm assuming you're testing from the master branch?)

**Comment by jlam55555** [comment] 2020-08-11 17:09
Closing due to lack of detail. Likely to be related to the issue in the above comment.

**Closed by jlam55555** 2020-08-11 17:09 UTC
